### ISSUE TITLE
Docs: The website loads, and then immediately turns entirely black

### ISSUE THREAD

**Issue by ItsHarper** [microsoft/TypeScript-Website#1216]
**Page URL:** <https://www.typescriptlang.org/> 

**Issue:** The entire site turns black, blank, and unusable

**Browser:** Verified in Chrome and Firefox, and a coworker sees the same thing.

**Comment by glashtin** [comment]
Same for me but it is white.  There is a number of javascript errors in the console log.

**Comment by camchenry** [comment]
I am seeing the same issue. These are the error messages that I see in Chrome 86:
![image](https://user-images.githubusercontent.com/1514176/95365771-9440db00-08a0-11eb-90d2-45c9058685d3.png)

**Comment by orta** [comment]
Looks like the official MS Cookie banner JS which we need to have in there is crashing, this is fixed by https://github.com/microsoft/TypeScript-Website/pull/1217 which is [deploying ATM](https://github.com/microsoft/TypeScript-Website/actions/runs/293903540) 

If you want a work-around while that happens, disable JS on the TypeScript website and it will work fine

**Comment by beremour** [comment]
Same thing for me (Safari 14)

<img width="880" alt="Screenshot 2020-10-07 at 22 56 27" src="https://user-images.githubusercontent.com/14082299/95369315-b8c4a380-08f0-11eb-8433-1348a1f1a818.png">

**Comment by orta** [comment]
The deployed fix it 👍🏻
