### ISSUE TITLE
Idea: Define innter table borders

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1221]
The table [on this page](https://www.typescriptlang.org/docs/handbook/jsx.html) is super hard for me to read.

![image](https://user-images.githubusercontent.com/972891/95396224-471b3400-08b5-11eb-9a91-83f5b898affb.png)

It feels super unclear to me which content goes in which column. Seems like the obvious solution is just to add inner table borders.

**Comment by SMAKSS** [comment]
Well, I agree maybe the best option for us here is to use full borders for inner elements, but I think we got a couple of other options here. So I will briefly describe them:

1. We can use `text-align: center;` for the whole table, which makes it a little more clear but not that much. 
Here how it will look:

   ![text-center](https://user-images.githubusercontent.com/32557358/95471725-18718c00-098f-11eb-822c-824f17e0582e.jpg)

   To make a little more readable, we can add the `width: 100%;` to table itself, then remove the `display: block;` to let the table fill the available space in the row. **But we should keep in mind due to `display: table;` nature the table won't be scrollable in the responsive view, so we have to add a media query and make its display, block once again for small devices**.
Here how it will look:

   ![text-center-and-width-100](https://user-images.githubusercontent.com/32557358/95472445-ea407c00-098f-11eb-9759-be8dc9cb6fbe.jpg)

2. To avoid many unnecessary lines and borders in the table we can just add some for dividing purposes. Well, it won't look very good at all I guess, but there are two versions of bordering here:

   i. With the border gaps

   ![border-right-with-gaps](https://user-images.githubusercontent.com/32557358/95473959-7606d800-0991-11eb-97ac-0053fc4b9cc5.jpg)

   ii. Without the border gaps

   ![border-right-without-gaps](https://user-images.githubusercontent.com/32557358/95473969-7901c880-0991-11eb-8d38-eba8a4eee79b.jpg)

3. And the final option is bordering the whole inner elements which again got two versions:

   i. With border gaps

   ![border-with-gaps](https://user-images.githubusercontent.com/32557358/95474901-83709200-0992-11eb-8f4b-2dccf57e557f.jpg)

   ii. Without border gaps

   ![border-without-gaps](https://user-images.githubusercontent.com/32557358/95474936-8b303680-0992-11eb-9678-23efbac22ac2.jpg)

And as I said earlier I think the very last one is a better and reasonable option for us here.

**Comment by orta** [comment]
I think the easy answer is that we should left align those titles to match the content and make sure it feels like there's enough padding between items. This is likely a 'this table looks bad, but this other table looks good in this style" case.

Perhaps it could make sense for larger tables to have an alternating background color too

**Comment by SMAKSS** [comment]
> I think the easy answer is that we should left align those titles to match the content and make sure it feels like there's enough padding between items. This is likely a 'this table looks bad, but this other table looks good in this style" case.
> 
> Perhaps it could make sense for larger tables to have an alternating background color too

Yeah, this is a really good option too, I was dumb enough to not think about this one. 😁
