### ISSUE TITLE
Docs: undocumented overloaded unction declaration syntax

### ISSUE THREAD

**Issue by olivier65** [microsoft/TypeScript-Website#1348]
**Page URL:** https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html

**Issue:** On the [tsd GitHub page](https://github.com/SamVerschueren/tsd) you find this overloaded function declaration:
```
declare const concat: {
	(value1: string, value2: string): string;
	(value1: number, value2: number): string;
};
```
Unless I am mistaken that syntax is not covered in the declaration reference.

**Recommended Fix:** Flesh out the declaration reference.

**Browser:** Not browser-related.

**Comment by orta** [comment]
Tricky, we do have a section on [overload function declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#overloaded-functions) but it uses the `function` syntax instead of a type with callable indicator. 

I'm not too sold on the need to cover every possible syntax permutation in this doc though, so I'll leave this open and see if I change my mind.
