### ISSUE TITLE
Playground: Loading in IE11 stuck on "Downloading TypeScript"

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/TypeScript-Website#1379]
Loading <https://www.typescriptlang.org/play> within IE11 never completes -- it gets stuck on "Downloading TypeScript".

Looking at the F12 Developer Tools, it appears that there are several errors preventing the scripts from executing:

![image](https://user-images.githubusercontent.com/2230453/100471393-0c50a380-308f-11eb-87e8-e0e290c78965.png)

I am not advocating that TS Playground should support IE11 -- in fact, I believe Monaco Editor has dropped support for IE11 some time ago -- but I think it'd be nicer if the page showed a message like "Your browser is not supported, please use a modern version of Edge / Chrome / Firefox / Safari", rather than silently erroring out and staying stuck...

**Comment by orta** [comment]
Yeah, looks like I can probably wrap the require for monaco in a try catch and show a message if that doesn't load.

**Comment by Zlatkovsky** [comment]
Awesome! Out of curiosity, how often does the site deploy (e.g., now that you've merged this -- or other changes -- in, how soon will it reflect on the running site)?

**Comment by orta** [comment]
[Staging](http://www.staging-typescript.org/) is every merge, the site auto updates from staging to prod every Monday unless we request a specific update via [this workflow](https://github.com/microsoft/TypeScript-Website/actions?query=workflow%3A%22Monday+Website+Push+To+Production%22) - since you asked, I just ran it.
