### ISSUE TITLE
typescriptlang.org does not support https without www

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-Website#14]
Expected: site should default to https.

Actual: does not load.

**Comment by styfle** [comment]
I had this issue as well since my browser suggested https://typescriptlang.org and I was greeted with a `NET::ERR_CERT_COMMON_NAME_INVALID`. I just assumed the whole site was down, didn't even consider `www`.

The issue is the certificate is for `oneroute.microsoft.com`:

> This server could not prove that it is typescriptlang.org; its security certificate is from *.oneroute.microsoft.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

[See screenshot](https://user-images.githubusercontent.com/229881/117996358-18b07c00-b310-11eb-9f3c-d4054f11b24c.png)

**Comment by orta** [comment]
This is fixed
