### ISSUE TITLE
Bug workbench: bad cache state crashes page

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript-Website#1550]
Bug workbench is stuck on "Downloading TypeScript," but loads fine in a private window.

Console error:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/3277153/107127810-7b0b6380-686d-11eb-87c3-2a9e93bfa56b.png">

**Repro:**

Not sure how to get into this state. But I’ll avoid clearing my cache if you want me to help debug next week.

**Comment by orta** [comment]
Looks like a bad monaco build on master at some point which poisoned the browser cache for monaco, happened to me too.

The fix is to move to the same type of 'ask for the latest nightly build version from a [rando JSON](https://github.com/microsoft/TypeScript-Make-Monaco-Builds#cdnd) file' approach the playground uses in order to ensure URLs are totally unique
