### ISSUE TITLE
Duplicates in JS output 

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#162]
http://www.typescriptlang.org/play/index.html?alwaysStrict=false&ts=3.8.0-dev.20191221&ssl=12&ssc=1&pln=12&pc=2&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAsAKG8AVHtqHqAGID25AdEYVsRAA4CGATswLagDeAqgEoAZAL6gxoAK6sANuPEAhNjXolwLdl27RIrAJYA7AOaip0qolbIAZqEUAvZQ3CXIU-T216jogIoSHtMDYVhL68JC65O5WlAAU3KAW1qDCAJQ8ROIubomWVgDc2MJAA

Try toggling one of the [grayed out options](https://github.com/microsoft/TypeScript-Website/issues/161)

![image](https://user-images.githubusercontent.com/972891/71384625-42d89100-2597-11ea-8d46-77b4e3deba46.png)

**Comment by orta** [comment]
This seems to happen with other things too (try pressing enter on that page) - it's running through the exact same code-paths as the ts version, so maybe there's shared state which is reset in TS but not JS?

**Comment by IllusionMH** [comment]
Is it possible that second editor (d.ts) contributes to the same program because rendered in monaco editor?

As I can see - as soon as you have function definition in JS editor it shows that this function has 2 overloads (my assumption is 1 from JS editor and 1 from d.ts).

As soon as you press enter - it adds 1 more definition from JS to already existing in d.ts (or the other way 1 new created from JS and extra - added from d.ts content). However it desn't explain why firt duplication has JSDoc comment and other don't.

**Comment by orta** [comment]
Ah, I see what you're talking about! That's feels like a really accurate guess. I'm less worried about it now, because it's fixed in v3 where I use the compiler API directly as a one-off. 

This means it doesn't show the bug, https://www.typescriptlang.org/v2/en/play?useJavaScript=true#code/PQKhAIAEBcE8AcCm4DeAeAKgPgBQEMAucDASnAF4twcAjI0iqjAX3BGACgBjAewDsAztHBcArgCdxAS0QATAGKi+XaFP4VweRuBraaAbg7d+Q8NEQAPaAEYNAIgAWiADbOedw70HDzVgEz2ALJ40Kp4HkZepr7QAMwaYpIyCkoqanw4MdYkmZbQfiSGRsbeZnkALAkS0nKKyqr8uVbZONZ+sYXgwMDgfDzgiJI84uBSfOAAUgDKHEA

**Comment by IllusionMH** [comment]
Not sure if all in reply is related to duplicated output in .d.ts editor in v2.
Second paragraph looks related to #203 (where v2 doesn't show errors at all, but v3 works fine, except no errors in editor)
