### ISSUE TITLE
Suggestion: make `/// <reference types="module" />` work

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript-Website#165]
Obviously, this requires fetching a tarball over npm, decoding it, and reading the relevant modules, a fairly involved and non-trivial process. But it'd be really fun to just break out and see what React code looks like by just doing something like this in the playground:

```tsx
/// <reference types="react" />
/// <reference types="react-dom" />
import React from "react";
import ReactDOM from "react-dom";

class Hello extends React.Component {
    render() {
        return <div>Hello, world!</div>;
    }
}

ReactDOM.render(<Hello />, document.getElementById("app"));
```

**Comment by orta** [comment]
I don't think I'll ever try to support runtime module grabbing for correct evaluation of source code in an app, that's why there are "Export as Code Sandbox" or "Export as StackBlitz" 

From a type perspective though, that code [works fine](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWRYmAEQHkBZObXAo9GAWgBNcZcuTQAbFAGcJcABJJRoiHCQAPGEgB2facm4A6AMK5IGzfADe5ONbhEtSKAAoAlHEs2PtpDACuUDXAAPHzAAG4AfHIKEAA0cADu0KJ8AISBAPQh4RQeAL7k+eS6GEzMenZ8Do6BUYpw6eFxAmg+IGZ6AObeAKKiSG0aMABCAJ4AknyO+ChgYPjOzqRAA) (because the playground has its own automatic type acquisition)

**Comment by isiahmeadows** [comment]
@orta I wasn't suggesting fetching `react` to ensure it runs, but `@types/react` to ensure it validates, if that helps clarify.

**Comment by orta** [comment]
Ah, no worries - it's been doing that for a while now! (though it just uses the named imports, I think it would still work with just the references too)

https://www.typescriptlang.org/play/?jsx=2#code/FASwtgDg9gTgLgAgEoFMCGBjRAzGUwIBEM6WhA3KJLIqpnACIDyAsgrvkSfQLQAm+CsGAYANmgDOEhAAkUo0VAQoAHnBQA7PtLpYAdAGF80DZsQBvYAmsISWlDAAUASgSWbH2yjgBXGBoQAHj4QADcAPjkFKAAaBAB3WFE+AEJAgHoQiMoPAF9gfOBdRlY9Oz4HR0CoxQR08LiBDB8wMz0Ac28AUVEUVo04ACEATwBJPkdCNAgIQmdnciA

**Comment by isiahmeadows** [comment]
Yep, and confirmed with Mithril's type definitions, too: https://www.typescriptlang.org/play/#code/FASwtgDg9gTgLgAjAGgQbwMJUlAdgU1zgF8EAzGbBAIjBDgAsYQAbagbmGDIFdcBjOCDwIAEvhYsoACgCUALgRYcBIgB40xAHzpgCfQhj44PGLl0HLCAG4h8Ad0VyEAXh1hp1ACYhr1VNTiklCo9rAsXgCE1LLIegbEnMRcYAB0YFB8cNJeUPw8YIRwqQDmxgCiLPiFRABCAJ4Akl6eAIYQEDGRqEFSsuxAA

Probably should've actually tested this first... 🙃
