### ISSUE TITLE
Docs: Convert Twoslash inline results to not just be a comment

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1655]
**Page URL:** All docs pages

**Issue:** 

Today the way we represent the inline LSP queries is via ASCII compatible UI:

```ts
type Greeting = "Hello, world"
type QuietGreeting = Lowercase<Greeting>
//   ^ = type QuietGreeting = "hello, world"

type ASCIICacheKey<Str extends string> = `id-${Lowercase<Str>}`
type MainID = ASCIICacheKey<"MY_APP">
//   ^ = type MainID = "id-my_app"
```

This was the cheapest way to test out the idea, and it was good enough for shipping:

![Screen Shot 2021-03-11 at 6 54 20 AM](https://user-images.githubusercontent.com/49038/110747703-a3083100-8236-11eb-8070-9bb2ce697496.png)

**Recommended Fix:** 

I think we should _visually_ distinguish these callouts as not living in the code more

![Screen Shot 2021-03-11 at 6 55 23 AM](https://user-images.githubusercontent.com/49038/110747796-c337f000-8236-11eb-9751-e895eed5e95d.png)

In rough:

 - Underline the selected identifier
 - Center arrow under the underline
 - Align text with the left edges of the identifier 
 - Don't require JavaScript to position the popover

Nearly all this work will live in shiki-twoslash (+ some CSS)

**Comment by hahmadia** [comment]
I'd like to take a stab at this

**Comment by hahmadia** [comment]
Hi @orta,

1. How would you recommend I go about finding the word? I'm currently in utils.ts doing a r.lsp === targettedWord where         const targettedWord = lspResponsesInToken.filter(response => response.text === (queries.length && queries[0].text)).pop()?.text; . I'm not sure if this is the best way to go about it or if you had a better approach in mind. The problem I'm having with this if a line has the same word several times in the same line, it will be underlined in all of it's instances rather than the one I'm pointing too.

2. The hardest part has been doing the little popover on the bottom. How do I get it centered? What do you recommend? I've spent a day or two on this and I can't seem to get it.  Will it be in the same html tags as data-lsp generated in utils.ts or no? 

3. I've been curious but what is a LSP and a token. Is token just another way to say word ? Like const is a token?

**Comment by hahmadia** [comment]
I noticed wikipedia ticket also had popovers so not a bad idea to learn how you want me to do them. In the past, I've always had access to bootstrap or some sort of UI library that did them automatically but never implemented them myself.

**Comment by orta** [comment]
You should be able to get the text range which needs highlighting from the [query via the start and length](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/ts-twoslasher/test/results/tests/queriesWithSpaceBefore.json#L5-L15) - which can then be used to figure out how far along in the line it should be

A token is a shiki token, basically a "color" in the syntax highlighting -  I'd make a new line and add some left offsets, it just needs to look like popover, it doesn't need to act like one. I'd expect it to be different HTML tags

LSP = roughly queries to TypeScript
