### ISSUE TITLE
Playground: Error text sometimes not shown

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript-Website#1682]
We don't always see error text in the Errors pane, even when errors exist

![image](https://user-images.githubusercontent.com/6685088/111225466-11355680-859d-11eb-85fc-f2223645091c.png)

**Repro:**

https://www.typescriptlang.org/play?ts=4.3.0-dev.20210315#code/JYOwLgpgTgZghgYwgAgMJwDYYEaINapgAeAPACoB8yA3gLABQyTyA9iAM4CuCS77AXMgAURQWQCUyALxUQnALbZoAbgbNWIaFBZRBQrYLggAnpJnIAbi2AATVfQC+DBjYgIMcKChicQCMMBsyAiYOPjkFEJgABbAAmihuAgExBHigla29i5uHl7BbOxgwcSC6FhJKaRFUKAA5hTZ9CEV+AB02KA2Qv5E4vYA9APIAHoJrcmE1WC1IA3IccggLMVwfMB1IHDYGChgLONhk6m+eMsA7iAUzs2J7Z0gNiRRsfHlR1UkNfUUZlSZNkivX6DCGo2QAHUdHh2MgYKAUOdohAQMh5EZOKFjMguNgisAwJwAnNkDEUHUUdBgAhScYAA4oFgwUnIuG+fyBEAMIA

**Expected behavior:** We should see a text rendering of the errors in the Error pane

**Actual behavior:** Blank space

**Comment by hahmadia** [comment]
Has this been resolved? I'm unable to reproduce
![image](https://user-images.githubusercontent.com/17804942/111530307-8178df00-8739-11eb-80bd-0c5ba2b43d38.png)

**Comment by RyanCavanaugh** [comment]
It's intermittent for me

**Comment by hahmadia** [comment]
Hey @RyanCavanaugh 

Ah! I got it now. You see my browser had cached the prior to Monday's playground (I was getting an older version of playground) launch but when I tried incognito, I was able to reproduce very quickly.

So the problem comes from this line right here
https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/sidebar/showErrors.ts#L26

If you copy the code you provided, and then do `CTRL + X` (Cut) and then repaste it, you notice that errors are not displayed. That's because when you cut the code, it returns without setting `prevMarkers = []`. When you pasted it again, the `JSON.stringify(markerIDs) === JSON.stringify(prevMarkers)` evaluates to true which immediately returns on line 33 without updating the `No Errors` display. 

I've created https://github.com/microsoft/TypeScript-Website/pull/1687 which addresses your issue along with some small optimizations.
