### ISSUE TITLE
Improve code sample output in playground

### ISSUE THREAD

**Issue by Johnrobmiller** [microsoft/TypeScript-Website#1769]
Regarding https://www.typescriptlang.org/docs/handbook/2/functions.html, there is not enough information provided in the docs to make use of hardly any of those code snippets.  There is a lot of essential information about their usage/implementation that is not being included here and feels cut off.  Going through the docs to learn how these types works feels, to me, a lot like reading a sentence that gets randomly and abruptly

**Comment by orta** [comment]
This issue is tricky to think of some actionable response. My best guess is that perhaps you're expecting TypeScript to explain how JavaScript function works, our documentation aims to sit on top of an understanding of JavaScript and to explain how types affect that code. Knowing that does it change your opinion? If not can you provide some examples?

**Comment by Johnrobmiller** [comment]
> This issue is tricky to think of some actionable response. My best guess is that perhaps you're expecting TypeScript to explain how JavaScript function works, our documentation aims to sit on top of an understanding of JavaScript and to explain how types affect that code. Knowing that does it change your opinion? If not can you provide some examples?

Thanks for responding, orta.  As hard as it might be to believe, I don't just come to these forums just to complain.  I also want to help out. 

If I could summarize what I would try to fix this problem in one sentence, I might say this: When the user clicks on the "try" button in the code snippet, there should be runnable code that uses what is being displayed in the article.  For example, this code...


```
type SomeObject = any;
// ---cut---
type SomeConstructor = {
  new (s: string): SomeObject;
};
function fn(ctor: SomeConstructor) {
  return new ctor("hello");
}
```
...is not runnable by itself.  It's not entirely clear how to use this code either, at least to me.  It would be helpful to provide some context, and this could be achieved by providing some runnable code to experiment with.

Hope this feedback helps,

John

**Comment by orta** [comment]
Interesting, your ask feels like "can we make all code samples runnable in the Playground, given there is a try button on all the code samples" - which is really far from what the issue title is. I'll change it.

I think we can make movements towards that but 'runs in playground' is in conflict with  'terse code samples which only do one thing'  - being able to run the JavaScript isn't the point of a lot of these code samples though because they're set up to show you the types not the JS. As a code sample in the handbook, that example is fine, it's only in the context of the playground where there are different expectations.

For the docs:

 - Anything above the cut is pretty safe game for changing, and I'm open to improves there

I think we could probably do better in the twoslash output for the playground "try" link:

 - We drop the try button on multi-file examples 
 - we auto remove `// ---cut---` from the code in the playground

**Comment by Johnrobmiller** [comment]
re, "title": You're right, that is a much better title.

re, "runs in playground": If I may attempt to paraphrase what you are saying, it seems that the goal of having "terse examples which only do one thing" is at odds with the goal: "runs in playground".  So, which goal should win out at the end of the day?  In my opinion, the goal that "wins" should be the goal that produces the better user experience given the situation.  Within the context of the handbook, the "terse examples" goal would produce a better ux, but the reverse is true for the playground.

re, "For the docs": I completely agree, and I'm definitely on board with the direction this is headed in. 👍

**Comment by orta** [comment]
The handbook as a whole is more important than an individual code snippet, it's better if they work on a playground but not at the expense of readability and general comprehension e.g. I wouldn't change

```ts
type SomeObject = any;
// ---cut---
type SomeConstructor = {
  new (s: string): SomeObject;
};
function fn(ctor: SomeConstructor) {
  return new ctor("hello");
}
```

to be

```ts
const constructor = (s: string) => {
  return {
   a: string
  }
};


function fn(ctor: SomeConstructor) {
  return new ctor("hello");
}
```

Because while that would run on the playground, it's far less useful as a way to understand how to define a constructor type - it doesn't even show it. 

In fact, I'm not even sure what I would change it to TBH but I'm open to PRs improving it.

**Comment by Johnrobmiller** [comment]
Hmm...  I'm fairly confused about something.  The code snippets in the playground should use the same types as the handbook, be readable/comprehensible like in the handbook, but they should also be runnable, right?

**Comment by orta** [comment]
No, they don't need to be runnable - running JavaScript isn't useful in explaining TypeScript. It would be nice to have, but shouldn't stand in the way of being a good code sample for the thing it is describing (which is type stuff)

The thing we're describing in that example can't be ran because TS erases it for example

**Comment by Johnrobmiller** [comment]
Hmm.. Well, the reason I opened this issue in the first place was that I was felt frustrated at the docs for not fully explaining how to use some of the types, such as the one above.  Honestly, if including/running some js in the code snippets would improve clarity, then, in my opinion, one should include/run some js.  The rule of "running js isn't useful in explaining ts" seems like a rule that would be useful in most situations, but not in all.  The same goes for the rule of keeping code samples terse.  I'm not a big fan of "black and white" rules like those that get blindly applied to all situations.  Perhaps it would be best to recognize the exceptions to those rules and adjust accordingly.  The type above might be a good example of when it's better to break those rules.

This is just my opinion though.
