### ISSUE TITLE
Docs: The ".d.ts Templates" pages are missing "Previous" and "Next" links

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript-Website#1816]
**Page URL:** The ".d.ts Templates" pages ([Modules .d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) through [Global: Modifying Module](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html))

**Issue:** Missing both "Previous" and "Next" links.

**Recommended Fix:** Apply similar solution to https://github.com/microsoft/TypeScript-Website/issues/1723#issuecomment-831980994.

**Comment by danBamikiya** [comment]
I don't think those are meant to have "Previous" and "Next" links. I observed the website's navigations and also checked the PR that closes the issue you're referencing, first the from the website those subsections that have navigation links are those that are meant to be learnt in order (not necessarily because they are subitems of that section) and the ".d.ts Templates" subsections seems like they are supposed to be each picked to be learnt (that means they don't rely on each other i.e they don't rely on the previous or next item) also the PR specifically sets the navigation to "false" for that subsection backing what I just said.
