### ISSUE TITLE
Playground: ts version shown in search bar and in dropdown are not same

### ISSUE THREAD

**Issue by saeedtlb** [microsoft/TypeScript-Website#1867]
Related to #1832 

In playground the search bar is look like this: typescriptlang.org/play?**ts=3.6.3** but the dropdown show the version **v3.6.2**

![Issue](https://user-images.githubusercontent.com/49431935/120207270-782fe680-c241-11eb-9b17-7b14cc6367c8.PNG)

I think the the [releases.ts](https://github.com/microsoft/TypeScript-Website/blob/9e73481f5b485695816b83e67677a406d310a853/packages/sandbox/src/releases.ts) file is the problem. the 3.6.3 should replaced with 3.6.2 because for search bar we generate the link base on those versions but for drop down we get the version with `sandbox.ts.version` and the version which shown by this code I think is true.

should I make PR? @orta

**Comment by orta** [comment]
I'm not certain what's actually going on here, because the 3.6.2 comes from the TypeScript version inside the JS but it was packaged with version 3.6.3. None of these values are hardcoded.

To make that issue go away I've started a build of 3.6.5 which should replace 3.6.3 in the menu and should ideally have the same number in its version

**Comment by orta** [comment]
It's not really possible to re-deploy a version of TypeScript that old with a modern version of Monaco is seems.

I'll either have to remove the 3.6 branch from the playground or hack the UI to pretend it's 3.6.2. I don't think either are good options and so I'm calling this a 'won't fix'.
