### ISSUE TITLE
Docs: Strict contravariance for callback parameters

### ISSUE THREAD

**Issue by captain-yossarian** [microsoft/TypeScript-Website#1874]
**Page URL:** https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#strict-contravariance-for-callback-parameters

**Issue:** Strict contravariance for callback parameters

**Recommended Fix:** Strict covariance for callback parameters

Consider next example:
```typescript
interface Mappable<T> {
  map<U>(f: (x: T) => U): Mappable<U>;
}
declare let a: Mappable<number>;
declare let b: Mappable<string | number>;
a = b; // expected error
b = a;
```
I think that such behavior caused by `covariance` rather than  `contravariance`.
Because if you remove `Mappable`, `b` is still not assignable to `a`
```typescript
interface Mappable<T> {
  map<U>(f: (x: T) => U): Mappable<U>;
}
declare let a: number;
declare let b: string | number;
a = b; // error in the same place,
b = a;
```
If I'm wrong, could you please explain me why? **Thanks**

**Comment by DanielRosenwasser** [comment]
`Mappable` is covariant on `T`, but only because the callback parameter `f` is strictly compared contravariantly.

The usual sequence of questions starts like this:

- Is a `Mappable<string | number>` assignable to `Mappable<number>`?
  - Are the types of `map` compatible?
    - Is the type `(f: (x: string | number) => ...) => ...` assignable to `(f: (x: number) => ...) => ...`?
      - Are the `f` parameters of these functions compatible?

And previously it would lead into

- Is `(x: string | number) => ...` assignable to `(x: number) => ...` *(this is incorrect covariant behavior)*
  - Are the `x` parameters of these functions compatible?
    - Is `string | number` assignable to `number` *(this is technically also incorrect covariant behavior with respect to the last question)*
      - No.
    - Is `number` assignable to `string | number` *(this is the correct contravariant behavior with respect to the last question, but...)*
      - Yes *(this incorrectly makes the overall check incorrectly succeed)*
- (In theory, we would check the reverse if the above checks failed - if `(x: number) => ...` is assignable to `(x: string | number) => ...`)

In 2.4+, TypeScript instead detects that both `f` parameters are callbacks. In turn, it will decide to only check `f` contravariantly with respect to the containing method, and signal that when comparing the parameters of `f`, *those* should also only be checked contravariantly.

Two contras make a co, and so the check on `x` ends up being covariant with respect to the check on `map`. I think that's where the misunderstanding here might've come from.

**Comment by captain-yossarian** [comment]
@DanielRosenwasser thanks for the explanation!
