### ISSUE TITLE
Playground: The selected font does not appear in the font dropdown list

### ISSUE THREAD

**Issue by mpstv** [microsoft/TypeScript-Website#1961]
The selected font does not appear in the font dropdown list. In addition to the fact that the selected font is not displayed, I also cannot select the default back.

![Peek 2021-07-14 21-43](https://user-images.githubusercontent.com/54762420/127028094-763013e9-5298-4ced-8b35-150a99707cf8.gif)

**Repro:**
1. Open playground.
2. Scroll to "customize" block.
3. Select any font instead default.

**Expected behavior:**
The page is refresh, the selected font is displayed in the dropdown list. When you click on the default font, it gets selected. 

**Actual behavior:**
The page is refresh, the selected font does not appear in the dropdown list. When you click on the default font, nothing happens.

**Comment by rijusougata13** [comment]
hello, can you assign me on this? I am working on this issue.

**Comment by orta** [comment]
Setting the playground to use the custom code fonts was reverted because it often ended up breaking the layout inside monaco. Today, the playground uses the default font in monaco (which is OS specific). You're welcome to take a look at this, but I'm probably not going to give it another look for a long time.

**Comment by rijusougata13** [comment]
In my localhost it is working.Language and the select list is also changing.This issue cant be reproduced in localhost.
