### ISSUE TITLE
Docs: Heuristic to use interface notation. 

### ISSUE THREAD

**Issue by carpben** [microsoft/TypeScript-Website#2043]
**Page URL:** 
https://github.com/microsoft/TypeScript-Website/blob/064dc8d9d56829d5d403a2c329a95675c99b38b0/packages/documentation/copy/en/handbook-v2/Everyday%20Types.md#differences-between-type-aliases-and-interfaces

**Issue:** 
Comparing Type and interface notations, they are said to be: 
- very similar 
- A matter of personal perference 
- The main difference is that interface is open ended. 

Then as a heuristic it is recommended to use interface, unless type notation is required. 

I find it confusing because it is not clear what the heuristic is based on, and why it is presented. The only difference presented - interface being open ended - actually should weigh towards choosing type notation, as this way when you see a type definition you know what you get. 

My question is - Is it based on some practical reasons (not present in the text), or is it based on convention and tradition? 

Perhaps this dissonance should be resolved.

**Comment by orta** [comment]
That heuristic line comes after many paragraphs explaining the trade-offs and features which differ between `interface`s and `type`s - it's meant to be simple heuristic based off the _entire_ thing you've just read, and I'm wary about us editing the doc to repeat that context in the one-liner.

It all comes from the context above in the handbook with one exception which _isn't_ in the handbook which also helps `interface` in that `interface`s are often [quicker to type-check](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections) because we can safely cache them - however that's an implementation detail which can change over time.

**Comment by carpben** [comment]
This speed consideration (and the resource) you presented provided context to and helped me understand the heuristic. 

I understand that it might change over time, but if speed is consideration to chose one over the other, I think it should be presented before the heuristic. 

Perhaps add to the unordered list that is above the heuristic?

**Comment by orta** [comment]
No, I don't think so, we don't want to encourage people to cargo culting something which can be unpredictable to know and measure without deeper tracing (or more importantly, a strong understanding of how the internals of TS works).
