### ISSUE TITLE
Playground: dead links in "TypeScript with Deno"

### ISSUE THREAD

**Issue by tsxoxo** [microsoft/TypeScript-Website#2097]
See [here](https://www.typescriptlang.org/play?q=212#example/typescript-with-deno).

There are two import statements in this playground. They both lead to 404s. 

```
import compose from "https://deno.land/x/denofun/lib/compose.ts";
(...)
import concat from "https://deno.land/x/denofun/lib/concat.ts";
```

## Suggested Fix
Currently, these files can be found under a shorter path, omitting the /lib.

```
import compose from "https://deno.land/x/denofun/compose.ts";
import concat from "https://deno.land/x/denofun/concat.ts";
```

---

I could fix this - can anybody tell me about the procedure around here? 
Can I just open a PR or do I have to submit an issue first? Do I have to wait for the label [you can do this]?

Sorry if this is trivial, I'm new to the open source ecosystem and couldn't find any guidance in the Contributing section of the readme. 

Any tips or pointers would be appreciated!
Would love to contribute.
Cheers!

**Comment by orta** [comment]
No worries, this is something which would need building into the npm module [`@typescript/ata`](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/ata) which is in this codebase. 

My recommendation would be to add support for passing in the function `createGraph` from https://github.com/denoland/deno_graph which can then be loaded up in the browser at runtime in order to figure out all of the required files to acquire. I can help get deno_graph running in the Playground when the pieces are in place. Once the Deno files are downloaded, they should get wrapped by a `declare module` [like this](https://github.com/microsoft/TypeScript-Website/blob/c64d6d37b6ad05c074969beb2dbb9d8831e5e39b/packages/sandbox/src/typeAcquisition.ts#L164-L165) which would make TypeScript recognize the `http` urls as module identifiers which can be resolved.

( /cc @dsherret )

**Comment by tsxoxo** [comment]
I'm not the man for this job :). 
Thanks for the explanation. Helped me make my decision.
Replying to clear the way for anyone who's interested.
