### ISSUE TITLE
Idea: playground plugin for running typescript-eslint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-Website#2114]
**Improvement Idea:** Add a plugin that loads ESLint into the playground with typescript-eslint

**Why:**

To start, there's discussion of building a whole typescript-eslint playground in https://github.com/typescript-eslint/typescript-eslint/issues/168 and https://github.com/typescript-eslint/typescript-eslint/pull/3147. This would both save a ton of infrastructure-y work and let typescript-eslint use "the" standard TypeScript playground.

Additionally, I often use the playground to share examples of _"why aren't these types working?"_ investigations. It'd be really nice to be able to add [eslint-plugin-expect-type](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type).

**Alternative ideas:**

Well, a few folks have built their own (e.g. https://yeonjuan.github.io/typescript-eslint-demo), but that's a lot of work...

**Comment by orta** [comment]
Had a play around with @armano2's exceptional work on the that WIP eslint playground (that's exactly the sort of case which I abstracted out the sandbox for) - so _anything_ can be made as a playground plugin, but the biggest question is can you make the setup as ergonomic as https://typescript-eslint-armano.netlify.app/ - which I think is a mixed bag of trade-offs

First time user experience is going to be weaker. You'd have to have a link: like https://www.typescriptlang.org/play/?dtPR=56838&install-plugin=playground-eslint which opens with a "Are you sure you want to install this?" for the first time

Ensuring updates is a bit harder with the plugin because it's not 'update the site and the playground gets the update'. Personally, I'd recommend generating a rollup bundled version of typescript-eslint somewhere to decouple the version of the dep from the playground (which is roughly how the playground works with TS versions) anyway though.

But yeah, that could be done as a plugin then

**Comment by armano2** [comment]
> that's exactly the sort of case which I abstracted out the sandbox for

sandbox is actually really great, its simplifies a lot of things, typescript-eslint playground relies on it heavily https://typescript-eslint.io/play/

are you still planning to add plugin to typescript website for it?

**Comment by orta** [comment]
Me? No,

I especially wouldn't want to compete (as I don't work on the TS website for my job anymore) and probably wouldn't be good at keeping it up to date, me + the TS team ensure that the playground infra keeps running (which ensures new sandbox builds etc) and that's enough. 

If you're pretty stable on how URLs work, we could have an 'export to eslint playground' button (like we do for the AST explorer) in the TS playground's export dropdown, which I think would be cool

**Comment by JoshuaKGoldberg** [comment]
> have an 'export to eslint playground' button

I love it! Yes please! 🎉
