### ISSUE TITLE
Docs: Confusion about when allowSyntheticDefaultImports is true

### ISSUE THREAD

**Issue by joebowbeer** [microsoft/TypeScript-Website#2169]
**Page URL:** 

https://www.typescriptlang.org/docs/handbook/compiler-options.html

https://github.com/microsoft/TypeScript-Website/edit/v2/packages/documentation/copy/en/project-config/Compiler%20Options.md

**Issue:** 

The documentation is confusing regarding when `allowSyntheticDefaultImports` is true.

The `esModuleInterop` documentation says enabling it will also enable `allowSyntheticDefaultImports`. However on this page, the `allowSyntheticDefaultImports` documentation says that it will be:

> `true` if module is `system`, or `esModuleInterop` and module is not `es6/es2015` or `esnext`, `false` otherwise.

It is not clear for example, what happens by default if `esModuleInterop` is true and module is `es2019`.

**Recommended Fix:** 

TBD

**Comment by sapphi-red** [comment]
It seems the `allowSyntheticDefaultImports` documentation should be "`true` if module is `system`, or `esModuleInterop`, `false` otherwise".

v4.7.4: https://github.com/microsoft/TypeScript/blob/76401adba33b71e70d76961d7d66064243be0243/src/compiler/utilities.ts#L6432-L6438
v4.4.4: https://github.com/microsoft/TypeScript/blob/01de6ff2ecdc6175727f7f999b887519d40ca115/src/compiler/utilities.ts#L6121-L6127
