### ISSUE TITLE
Docs: Nits for the cheat sheets

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#2228]

**Comment by orta** [comment]
> const inputLength =
  (typeof input === "string" && input.length) || input

Nit: if input is "", inputLength will be "", not 0
Nit: CFA doesn't have keyword highlighting on anything but the first codeblock under "Assignment"
Nit: const is highlighted in blue on Class but in red on other pages

> See that's exactly why I dislike using logical operators that way.  If ?? isn't applicable I'd rather write out the ternary or if statement

**Comment by orta** [comment]
> Super-Nit: in Interface, new is highlighted in red and followed immediately by the paren; in Type, new is plain black and followed by a space

> Nit: const is plain black in Interface

**Comment by orta** [comment]
> What does "everything but 'static' matches" mean on the types cheatsheat?

**Comment by tjjfvi** [comment]
Syntax highlighting nits:
- `const`:
  - Red in CFA > Assignment, Type
  - Black in CFA, Interface
  - Blue in Class
- `new`:
  - Red in Interface, Class
  - Black in Type (+ followed by space)
- `get`/`set`:
  - Red in Class
  - Black in Interface
- Identifiers: inconsistent blue / black
- Types: inconsistent green / black
- Comments: some comments in Class are a light green, difficult to read due to low-contrast
- `implements`: black in bottom-right corner of Class, red elsewhere
- CFA has no syntax highlighting except for comments and the first codeblock in Assignment

**Comment by tjjfvi** [comment]
Property endings use mixed newline / semicolon (see e.g. Interface > Overloads)

**Comment by tjjfvi** [comment]
CFA > Assertion Functions uses slanted quotations

**Comment by tjjfvi** [comment]
CFA > Expressions:
```ts
const inputLength =
    (typeof input === "string" && input.length) || input
```
As mentioned above, if `input` is `""`, `inputLength` will be `""`. This could be replaced by a ternary, but if you wanted to specifically showcase the interaction with `&&`, consider:
```ts
if(typeof input === "string" && input.length > 5){
  ...
}
```
(in fact, I'd say have both an `inputLength` with a ternary and something like ^ to show that it works with both)

**Comment by orta** [comment]
https://twitter.com/NoriSte/status/1483107658861359112

**Comment by orta** [comment]
Think that's all existing feedback handled (and added my own now I've been away from it enough to have fresh eyes) - https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=3414%3A9

**Comment by orta** [comment]
Will do the asset update on friday

**Comment by tjjfvi** [comment]
Some remaining syntax highlighting inconsistencies:
- Black `const` under Interface > Get & Set, CFA > * > Usage
- Blue `const` under Class > Common Syntax
- Black `type` under CFA > Discriminated Unions
- Blue `readonly` under Class > Common Syntax
- Black `get` under Class > Decorators and Attributes
- Black `this` under Class > Abstract Classes, Class > Generics (v.s. purple (?) in Class > Common Syntax) (consider red to match other keywords?)

Potential inconsistencies:
- Consistently black keywords:
  - `new` under Class, CFA > Assertion Functions
  - `if`, `instanceof`, `throw` under CFA
  - `asserts`, `is` under CFA > Assertion Functions (debatable)
  - `super` under Class > Common Syntax
  - `import` under Type > Type from Module
- Green types under Class > Common Syntax (in `implements`) (same green as adjacent comments; somewhat confusing)
- Identifiers inconsistently blue/black (maybe intentional for emphasis?)
- Blue `!` (in `!:`) under Class > Common Syntax (compare all-black `?:` on the line above)

**Comment by orta** [comment]
Alright, I think the inconsistencies I've left in now are generally all ones I want 👍🏻  (I opted for field name identifiers only to have colorings )
