### ISSUE TITLE
Idea: Be able to highlight and copy code snippets

### ISSUE THREAD

**Issue by brentlintner** [microsoft/TypeScript-Website#2324]
**Improvement Idea:**

Be able to highlight and copy code examples. Right now [you can't](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html), except "try it".

**Why:**

Sometimes I want to be able to lazily copy something to try out locally, where I work 100% of the time. This just restricts it for no reason, and I immediately think it's an image. Some examples don't even have the try feature, so this feels like a significant UX issue for me.

**Alternative ideas:**

Allow default browser behaviour for code snippets.

**Platform**

* MacOS Chrome ARM (100.0.4896.75)

Thanks so much and appreciate the time!

**Comment by orta** [comment]
You make it sound like it's not possible to select the text and copy it in the page? If that's the case, then what is your browser? But all code samples should be OS-level copy and pastable, if it's not that's a real UX issue.

From my perspective, adding a button to copy each code sample seems _ok_ - it's a feature that's useful for mobile where copy & pasting is tricky but far less valuable but when working with code on a desktop (which is about 95% of the traffic) it's value is low. I'd be open to a small bit of JavaScript in documentation pages which adds a copy command to code samples, with a button to the left of 'try'.

Any compiler backed code sample gets a try button because it can be guaranteed to run in the playground, but I think the copy button could exist on any code sample.

**Comment by brentlintner** [comment]
I'm seeing this running MacOS Monterrey w/ Chrome ARM (100.0.4896.75) (Macbook Pro 14")

Just checked on x86_64 Windows 11 (Chrome), and I can copy fine so must be a MacOS issue.

Here is what I see on MacOS ARM FWIW:

![2022-04-07 18 43 40](https://user-images.githubusercontent.com/93340/162331809-9769d27d-e454-48df-8f02-e5ee8e47e077.gif)

**Comment by brentlintner** [comment]
Given I can actually just copy as normal, that is totally enough IMO, but the button idea is cool too!

**Comment by brentlintner** [comment]
Update: I realized it does actually copy to the clipboard if you mouse just right and hit CMD+C (but there is no highlight styling).

**Comment by orta** [comment]
Yeah, I think your mouse selection is somehow not showing - just I tested on linux chrome dark/light, and macos crome dark/light and didn't get a repro - perhap you have browser extensions doing something to the site?

**Comment by brentlintner** [comment]
Interesting. I don't have any extensions that mod.

I asked a few devs at work to reproduce if they could as well. One ran into it on a M1 Pro 14", then randomly couldn't after restarting chrome. Another dev couldn't reproduce at all. So idk, presuming it's a local issue for me, idk what. 😆 

I did some more testing though, and FWIW:

* Safari (Dark Mode) highlights but selection is black;
* Safari and Chrome (Light Mode) highlights are visible
* Chrome (Dark Mode) highlights are invisible

Welcome to close btw. Thanks again for the time!
