### ISSUE TITLE
Docs: Please improve vague "Namespaces and Modules" page

### ISSUE THREAD

**Issue by SetTrend** [microsoft/TypeScript-Website#2345]
## Page URL

https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

### The distinctive information presented on that page is very sparse.

Many technical questions are left unanswered, for instance:

1. What's the difference between `import`ing a module/namespace?
2. Are there ambient namespaces?
3. What's the difference between a namespace and an ambient module?

<br/>

### The section [Pitfalls of Namespaces and Modules ► `/// <reference>`-ing a module](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#-reference-ing-a-module) doesn't make sense

Here's a commented version, depicting various confusing statements:

**(a)**
> A common mistake is to try to use the `/// <reference ... />` syntax to refer to a module file, rather than using an `import` statement.

**(b)**
> To understand the distinction,

… between what?

**(c)**
>  we first need to understand how the compiler can locate the type information for a module based on the path of an `import` (e.g. the `...` in `import x from "...";`, `import x = require("...");`, etc.) path.

… do we really need to know how the compiler _**resolves paths**_ to see the distinction?

**(d)**
> The compiler will try to find a `.ts`, `.tsx`, and then a `.d.ts` with the appropriate path.

**(e)**
> If a specific file could not be found, then the compiler will look for an ambient module declaration. Recall that these need to be declared in a `.d.ts` file.

… didn't the compiler already "look for an ambient module declaration" in step **(d)**?? The third file extension there was a `.d.ts` file extension already. So, does it look twice then? What' the way the compiler would look for an "unspecific file" then?

**(f)**
> The reference tag here allows us to locate the declaration file that contains the declaration for the ambient module. This is how the `node.d.ts` file that several of the TypeScript samples use is consumed.

… er … didn't the heading **(a)** read: _"A **common mistake** is to try to use the `/// <reference ... />` syntax to refer to a module file, rather than using an `import` statement."_? — And now you're actually saying that you are in fact using `/// <reference ... />` syntax to refer to a module file, rather than using an `import` statement.??? … Huh?

<br/>

### [Trade-offs of Modules](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#trade-offs-of-modules) is not helpful

> Just as there is a one-to-one correspondence between JS files and modules, TypeScript has a one-to-one correspondence between module source files and their emitted JS files.

This correlation is guff. What should the correlation be between (a) unrelated JS source files on one hand and JS module files on the other hand, and (b) related TS module files compared to their transpiled JS module counterparts?

## Recommended Fix

Do whatever you feel is appropriate to solve this issue by improving the documentation content.

**Comment by aleixsuau** [comment]
Hey Typescript, thanks for your work.

I'd like to add to this issue, I believe the reasons explained in [Needless Namespacing](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Namespaces%20and%20Modules.md#needless-namespacing) are not enough to support the conclusion. 

* It seems that you recommend always importing complete modules instead of the single parts needed, am I right? Could this affect the final bundle size?

* Module imports rely on the single developer too much, I believe this is not good for consistency since it assumes that:

1 - The developer will always do `module` imports, but single `imports` are fairly common (and preferred by auto-import tools?):

````
import { User } from '@myProject/course...';

// .... and a few lines below
const user: User; // is this the Course User or the AdminPanel User?
````

2 - The developer will name the module correctly and consistently:

````
// classA.ts
import * as shapes from "./shapes";

// classB.ts
import * as shapeModels from "./shapes";
````

It seems that namespaces could solve all those issues (consistent naming, auto-imports, autocompletion, reinforcing the domain scope (Course.User)...) and I can't see any trade-off, especially when related to types/interfaces.
