### ISSUE TITLE
Docs: Missing html files in navigation

### ISSUE THREAD

**Issue by MansurAliKoroglu** [microsoft/TypeScript-Website#2518]
Two pages I can find in code and go to html by using url but they are not in nav. Is this desired behavior?

**Page URL:** https://www.typescriptlang.org/docs/handbook/2/type-declarations.html and https://www.typescriptlang.org/docs/handbook/2/understanding-errors.html

**Issue:** Two documentation pages missing in nav

**Recommended Fix:** Probably edit `generateDocsNavigationPerLanguage.js` file.

**Comment by orta** [comment]
Yeah, I think maybe the type-declarations one _could_ live in the declaration files section of the docs, but it was hard to find a space for it and we never came back for it

The understanding error sone never got fleshed out the idea was interesting but it's not good enough for the docs

So neither being in the nav is intentional right now
