### ISSUE TITLE
Outside contributions do not seem to be accepted anymore

### ISSUE THREAD

**Issue by datenreisender** [microsoft/TypeScript-Website#2585]
In https://github.com/microsoft/TypeScript-Website/blob/v2/README.md#contributing it says “This project welcomes contributions and suggestions” but looking at the [PRs](https://github.com/microsoft/TypeScript-Website/pulls) it seems like only internal changes are merged and outside contributions are ignored, like [the small fix I did four months ago](https://github.com/microsoft/TypeScript-Website/pull/2439). 

So, it seems to me, like for some reasons (no time for it?) outside contributions are currently not accepted anymore. 

If that is true, then please state so. And remove the “The TypeScript docs are an open source project. Help us improve these pages [by sending a Pull Request](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/handbook-v2/Object%20Types.md) ❤” from the bottom of the documentation pages.

It is frustrating to create a fix for something and then have it just be ignored.

**Comment by orta** [comment]
A potential answer: https://github.com/microsoft/TypeScript-Website/pull/2286

**Comment by andrewbranch** [comment]
To say that the transition of website responsibilities since Orta’s departure has not gone smoothly would be an understatement, so let me start by apologizing for the frustration.

Currently, nobody on the team is actively watching and triaging issues and PRs on this repo, and nobody is spending the majority of their time working on the website. Updates are being made on an as-needed basis to keep release notes and playground versions up to date, and even these often come late, at the reminders of folks in the TypeScript Discord. This is obviously not a sustainable situation but we are just beginning to come up with a plan for how to move forward.

Personally, I hope we can keep the website open source and work out a system for accepting PRs in a reasonable timeframe. Before we get to that, though, we need to fix a lot of our build and deployment infrastructure, which we’re currently investigating. At the moment, automated deploys are inexplicably broken and until today, nobody could build the website locally outside of Codespaces. We have some work to do on being able to reliably execute the most basic maintenance tasks before figuring out how to address the backlog of issues and PRs. This is going to take some time as we balance this with product priorities.

My hope is that within the next release cycle, we can communicate a plan for the website that includes updated expectations for community involvement. Again, I’m sorry for the way it’s gone in the meantime.
