### ISSUE TITLE
Docs: TypeSearch is down

### ISSUE THREAD

**Issue by assembled-wei-wei** [microsoft/TypeScript-Website#2645]
**Page URL:** https://www.typescriptlang.org/dt/search 

navigating from https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html#searching

**Issue:** it doesn't load

<img width="1555" alt="Screenshot 2022-12-15 at 1 13 11 PM" src="https://user-images.githubusercontent.com/116240265/207968404-eec54661-77db-4a90-b840-28f5ac6c2d2b.png">

**Recommended Fix:** 

some indication that this was removed intentionally

**Comment by orta** [comment]
This was intentionally removed in https://github.com/microsoft/TypeScript-Website/pull/2625 - though that section of docs could do with being removed, thanks

**Comment by assembled-wei-wei** [comment]
Ah I see. Does it make sense to also remove the out dated documentation in definitely typed as well?

**Comment by wbt** [comment]
Part of the justification for removal is the searches "the searches on https://npmjs.com ... indicate DT availability / types included."
Could someone post a screenshot with a circle indicating where that indication is? 
I'm not seeing it.

**Comment by JoshuaKGoldberg** [comment]
@orta @andrewbranch the aka.ms/types URL still points to the old resource. [A lot of community resources reference aka.ms/types](https://www.google.com/search?q=%22aka.ms%2Ftypes%22&oq=%22aka.ms%2Ftypes%22&aqs=chrome..69i57j69i58.1266j0j7&sourceid=chrome&ie=UTF-8#ip=1) - including, selfishly, my _Learning TypeScript_ book.

Instead of removing the types search completely, how difficult would it be to correct the bug reported in #2624? I'd be very willing to implement that fix if it's something I can do as an external contributor.

Or failing that / in the interim, there should at least be a _"this is gone now"_ / _"under construction temporarily"_ notice on aka.ms/types.

**Comment by dk8996** [comment]
I agree with @JoshuaKGoldberg this seems like very useful tool. Would fixing the bug report be a good path to bring this back?

**Comment by wbt** [comment]
A page with a tutorial about where to look on NPM/Yarn package search, with some screenshots and circles, could go up in place of the old page, at the same URL.  It seems like that would satisfy all raised concerns.

**Comment by SWBennett06** [comment]
+1 on at least having some indication on the landing page that the removal is intentional and, ideally, pointing out the recommended alternative. I'd wager there's dozens of "learn to TypeScript" resources pointing at this now dead link, which isn't a great experience for newcomers.

**Comment by andrewbranch** [comment]
I’ll review and accept a PR for a page that links to npm and yarn.

**Comment by wbt** [comment]
The issue as reported at the top of the thread still persists - is that because the closing PR hasn't rolled out yet or doesn't quite fix the problem?

**Comment by andrewbranch** [comment]
Right now, we deploy every Monday or as-needed, because busted Azure stuff means deployments require manual intervention. We are in the process to switching to newer Azure infrastructure that actually works, and will move to deployments on every push to the main branch at that time. So yeah, was planning on this shipping Monday.

**Comment by wbt** [comment]
OK.  
It's kind of a relief to hear that even a MS team struggles that much with Azure 😅.

**Comment by andrewbranch** [comment]
😅 

For a little more context, Azure Static Web Apps didn’t exist when the current infrastructure was set up, so right now it’s kind of jerry-rigged up to Azure App Service, which is really not made for serving static HTML. Every Monday, a GitHub Actions workflow runs that builds the static HTML and commits it to the SITE-PRODUCTION branch. There is supposed to be a web hook that tells Azure when there are new commits pushed to that branch, and that’s what is inexplicably broken. It might be user error, but we’ve been trying to switch over to Static Web Apps anyway, so I haven’t put much time into fixing it. We just go click a button once a week. From what I’ve seen so far, Static Web Apps seems pretty nice.

**Comment by wbt** [comment]
Same comment on GitHub then too 😅
