### ISSUE TITLE
Dead external link.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript-Website#2776]
https://github.com/microsoft/TypeScript-Website/blob/62f87a80f571762ff252eb38b53b890f9f864acb/packages/documentation/copy/en/release-notes/TypeScript%202.6.md?plain=1#L15

This link is dead, and I'm not sure what to link to instead.

**Comment by shuuji3** [comment]
While I couldn't find another URL for the page, it looks like the blog was down due to Heroku's decision to shut down its free plan.

I found the archived page by Internet Archive: http://web.archive.org/web/20220823104433/https://www.stephanboyer.com/post/132/what-are-covariance-and-contravariance Maybe we could temporarily replace the dead link with this one.

**Comment by agilgur5** [comment]
Looks like this was fixed by OP in #2808

**Comment by shuuji3** [comment]
Thanks for the heads-up.🙂  It seems that the new link was broken again so I'd raised a new PR to ensure the stable URL.
