### ISSUE TITLE
Should elaborate more on the way conflicts are handled in Interfaces vs. Intersections

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/TypeScript-Website#3071]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/objects.html#interfaces-vs-intersections

**Issue:** It says the following:

> The principal difference between the two is how conflicts are handled, and that difference is typically one of the main reasons why you’d pick one over the other between an interface and a type alias of an intersection type.

But then it doesn't elaborate on how the conflicts are handled. A link to any article explaining it would be ok.

**Comment by merintheressa** [comment]
Hi,

I would like to suggest an addition to the documentation to clarify how TypeScript handles conflicts between interfaces and intersection types.I believe this addition will help clarify the differences between interfaces and intersection types. If you think this explains the difference, please assign the issue to me and I will create a PR.



**Here is the proposed explanation:**


If interfaces are defined with the same name, TypeScript will attempt to merge them if the properties are compatible. If the properties are not compatible (i.e., they have the same property name but different types), TypeScript will raise an error.

In the case of intersection types, properties with different types will be merged automatically. When the type is used later, TypeScript will expect the property to satisfy both types simultaneously, which may produce unexpected results.

For example, the following code will throw an error because the properties are incompatible:

```
interface Person {
  name: string;
}

interface Person {
  name: number;
}
```

In contrast, the following code will compile, but it results in an invalid type:

```
type Person = {
  name: string;
};

type Staff = Person & {
  name: number;
};
```
In this case, Staff would require the name property to be both a string and a number, which is impossible and thus problematic.
