### ISSUE TITLE
Playground problem with serialisation of logs

### ISSUE THREAD

**Issue by artola** [microsoft/TypeScript-Website#346]
The serialisation of the logs is wrong.

- showing `null` in place of the expected `undefined`:
  `console.log([undefined]); // ==>  [LOG]: [ null ]`
- not showing existing keys:
  `console.log({foo: undefined}); // ==> [LOG]: {}`

**Comment by orta** [comment]
Cool, if someone wants to look into this, the code is here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/sidebar/runtime.ts#L115

**Comment by artola** [comment]
@orta The "print" function mentioned above is the culprit, `const isObj = typeof arg === 'object'` will be true for Arrays (and other types: regexp, dates, etc)) and `JSON.stringify(arg, null, 2)` can not handle them properly.

Are you using some other formatter already?  (something like recast)

**Comment by orta** [comment]
Nope, what you see it all there is, I aimed for simple and good enough.- happy for it to get extended to be comprehensive.

**Comment by ire4564** [comment]
As mentioned earlier, I also checked that the `JSON.stringify()` function does not work. That is why I tried a few attempts because I think I need to modify this. The way I thought of it is as follows. I hope you can comment on your opinion.

The attached picture is the result of testing the `stringfy()` function at the W3school site. As a result, we found that not having "" attached to the inner element returns nothing as a result, like this error we know. We found this to be a problem here.

One of the alternatives to the workaround is to parse this object and make it json again, then use `stringfy()`. I am trying to do this in this way, but I accessed the elements of an object using a for statement, but it seems that the value of the value(variable) is not recognized. Is there a good way? What do you think about this method?

![Untitled](https://user-images.githubusercontent.com/44183221/101753624-38036d00-3b16-11eb-9e0b-24a252cb8df2.png)

**Comment by h01010** [comment]
Taking `console.log({foo: undefined})` as an example,
now, In function `objectToText`, `{foo : undefined}` from `console.log({foo : undefined})` is recognized as an object, but `JSON.stringfy()` cannot handle it properly.

Then how about **extracting the `name`(foo in example) and `value`(undefined in example) from the `arg Object` and redefining the `toString()` function which can be called by `JSON.stringfy()` like below**?

![Untitled](https://user-images.githubusercontent.com/44168693/101757282-4d7a9600-3b1a-11eb-9682-2d9cac0c3bd7.png)
(This example doesn't work well, Im trying to find the proper way to extract the name and value...)

    
    
I already checked `JSON.stringfy()` on [`the 146th line of  runtime.js`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/sidebar/runtime.ts#L146) find and call this redefined `toString` function(above) like below.

![Untitled2](https://user-images.githubusercontent.com/44168693/101757461-89156000-3b1a-11eb-8b9c-485fdb0b85c1.png)
The '162 line' in above image is the log from the `JSON.stringfy()`.
Look at the 'toString' part, it calls `argToString()` which is redefined well.

**Comment by orta** [comment]
There's been improvements to the log printer since this issue:

- `console.log([undefined]);` shows undefined 🟢 
- `console.log({foo: undefined})` doesn't show the `foo: undefined` 🔴

**Comment by hahmadia** [comment]
Possible to close this if irrelevant? @orta

**Comment by orta** [comment]
I think there's still value in getting `console.log({foo: undefined})` to show the `foo: undefined`
