### ISSUE TITLE
Missing the playground link in the header

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript-Website#359]
It is hard to reach the playground from the top page.

**Comment by orta** [comment]
I'm afraid that's not going back to the old nav, maybe tools could also be a drop down 

Ideally once I get DNS access then I can set up `play.typescriptlang.org` which will make it very trivial to access.

**Comment by falsandtru** [comment]
Anyway I want to go to the playground from the first view to test the code. The modern languages such as Babel, Go, and Rust provide the link for the playground in the first view. TypeScript has deviated from this practice.

**Comment by thephoenixofthevoid** [comment]
I don't know if it's worth creating a separate issue, but anyway. 

On the page:  ***https://www.typescriptlang.org/v2/tools*** there is a link to playground ***https://www.typescriptlang.org/en/play***, which says: 
> "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

But slightly different link: ***https://www.typescriptlang.org/v2/en/play*** works as expected.
 I do realize that it's because the absolute link was used before to reference playground and it didn't survive prefixing with 'v2'. 

To me it's a bug: _a subsection of the site must work despite being prefixed and even deployed under many different prefixes and they should never get mixed unless it has been stated explicitly._ Just it doesn't show under ordinary conditions.

**Comment by orta** [comment]
I added this back when your browser is wide enough for it to fit

and I can't repro the `/en/` issue on staging ( `/en/` got dropped because it duped pages ) - happy to reopen if you can repro today
