### ISSUE TITLE
Wrong description about Typescript

### ISSUE THREAD

**Issue by matheusalbino** [microsoft/TypeScript-Website#588]
I'm confused about the description of Typescript on the website, in the topic "JavaScript and More" on section "What is TypeScript?" says:

![Screenshot from 2020-05-17 23-34-55](https://user-images.githubusercontent.com/6087948/82169188-16e7e000-9897-11ea-8924-910895f4b71a.png)

Because Typescript is a superset, not a language. I'm not certain if I understand correctly.

**Comment by orta** [comment]
TypeScript has always called itself a language, and as a language it can be called a superset of JavaScript. Due to TypeScript having all the features of JavaScript and more (types) 

Personly I prefer against talking in set theory on the landing page, which is why I use 'extends' or 'build upon' because the set theory audience is a slither of the general dev audience

Does that help clear it up?

**Comment by glaucia86** [comment]
cc: @matheusalbino the answer to your question.

**Comment by matheusalbino** [comment]
Yes, it's clear. Thanks!
