### ISSUE TITLE
Community Section of TypeScript Website 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#63]
[This was my original spec](https://user-images.githubusercontent.com/49038/65344034-8f7d8c00-dba4-11e9-8078-9f4ce2aaf853.png) for the community vertical section in the site.

My goals with this section:

- Help funnel people looking for info into the right place
- Highlight existing communities both online and offline
- Provide information for getting support and building the own
- Offer spaces for people already doing work to have it in a somewhat more 'blessed' way

I think we can use the TypeScript site as a way to bring these people together in a space they already are at.

I'd like to use this thread to discuss what this subsection is and could be. Sources of inspiration for this are [rust-lang.org/community](https://www.rust-lang.org/community), [peerlab.community](https://peerlab.community), [typescript.events](https://typescript.events) and the [react-native-community](https://github.com/react-native-community)

# Physical Events

### Conferences

We should have a section in the index which highlights upcoming conferences which are TypeScript focused, as well as a way to see links to the older ones (so you can watch past talks)

### Meetups

It would be good to provide central resources for people running meetups, this could be

- Docs on how to run meetups ([rust do a good job here](https://github.com/rust-community/events-team/blob/master/guidelines/program-guidelines.md)) we can build on these, or go solo too
- Design resources (templates etc)
- Sub-folders within the TS website for your meetup (from the looks of it, all the meetups use meetup.com - so maybe we can automate a lot of that for people?) - e.g. https://typescriptlang.org/community/nyc being a pretty wrapper to https://www.meetup.com/TypeScriptNYC/ via the meetup API

# Community organization

We could create/promote a TypeScript community discord - which could allow each meetup to have their own channels, and can encourage that to be a space to chat with others more. I know that @Haxified has done some good work here, and maybe we can bless https://discord.gg/rqAeTR5 as the right spot if it can have CoCs (and give the TS team admin rights also) etc.

This worked well for React Native in terms of the contributors to React Native + RN Community. Each project has its own room and repo.

### TypeScript Community Twitter

We could provide access to a shared @typescriptcommunity twitter, which uses something like [Twitter Together](https://github.com/gr2m/twitter-together/) to make PR based tweets, which gives us the chance to make sure it's all cool and to allow anyone to contribute. 

I'd like it to also be used to re-tweet good announcements, I think [`@rustlang`](https://twitter.com/rustlang) does a good job there. I think it's fine for the TS twitter to be focused on releases and big announcements, and this other one - maintained by the community can make it easier to raise visibility of interesting projects.

### Highlight Cool Talks

It'd be good to have an index with talks people have done on, or about TypeScript in an index somewhere.

### Link to newsletters

I know about TypeScript Daily, but are there more that folks recommend? We should help people find them

---

I'm probably missing things, this is still of a work in progress!

---

and a hat-tip to @karol-majewski for getting the ball rolling

**Comment by orta** [comment]
Some off the cuff ideas:

- Could there be a place to show off useful types and the libraries where you can get them? They could link to playgrounds with them to show off how it works

- Could there be some stuff about https://makecode.microbit.org ?

**Comment by jsjoeio** [comment]
Commenting so I can keep an eye on this - would love to help where needed!

**Comment by pspeter3** [comment]
This is a great idea. What feedback / ideas are you looking for?

**Comment by orta** [comment]
Ideas mostly at this point, I've got 3.7 bugs for a while and am in the process of starting to look at the v2 of the site where some of this can live. 

Maybe though some of it can be built out now though, I've already built some of the community infra for letting other merge PRs

**Comment by ddprrt** [comment]
I'm super happy that I found this thread via the TypeScript Daily newsletter :-) I'm doing typescript.events and currently working on a revamp of the site to feature a bit more.

Things that I'm working on at the moment:
- Getting a list of upcoming meetups via the Meetup API
- Showing upcoming and archived conferences
- A curated list of cool conference and meetup talk recordings around TypeScript

My inspiration was https://awesometalks.party/ https://reactjs.org/community/conferences.html and https://events.vuejs.org/

Looks like there's some common goals. :-) I'm happy to drop development of typescript.events and contribute to something official, if you need help.

I also like the idea of having a discord or similar to connect to other meetup groups. We are in the progress of finalising the date of tsconf.eu, and once we're live, I want to reach out to the European communities to bring as many people to the CfP and event. Having this one spot to reach out to everyone would be super helpful.

**Comment by orta** [comment]
Yeah, now [that meetup.com have started charging](https://www.theverge.com/2019/10/15/20893343/meetup-users-furious-new-rsvp-payment-test) - I think tying the infra directly to the meetup API is probably a bad call. I think this space is going to get really messy for the next year or two. 

#### Looking at what we can get done today

The site has a "connect" tab which redirects to `/community` - I think it might be reasonable to:

- convert the current page as-is to be a "connect online"
- add a "connect offline" which lists conferences and meetups like on https://typescript.events

Then we can start building that out as a jump-off page [similar to rusts](https://www.rust-lang.org/community) which redirects out to different pages?

**Comment by ddprrt** [comment]
As for Discord: Is the discord group still valid? I have troubles getting in with the invite linked in their group. I'm a discord newbie, though. So I figure it might be my problem.

**Comment by orta** [comment]
The TypeScript Community have started bootstrapping up a lot of infra:

- https://github.com/typescript-community
- https://github.com/microsoft/TypeScript-Website/pull/88 is getting CoCs added consistently across the TS meetups

**Comment by karol-majewski** [comment]
Hey! [TypeScript Wrocław](https://typescript.community/) here.

Instead of telling you what _I think should go to the Community section_, let me share a few insights into how we run our meetup group. My hope is this will shed some light on what are the common pain points associated with running an event and maybe spark an idea or two for how things can be improved by consolidating the tools and centralizing the processes.

## Tools

### Meetup.com

Unsurprisingly, we use Meetup to stay in touch with our guests.

**What it solves**

- Everyone attending live events in our city seems to be on Meetup. Not everyone is on Facebook. Not everyone is on Twitter. Software engineers tend to belong to many meetups groups, so it's convenient for everyone.
- Newsletters come in handy (e.g., when there's an unexpected change to the agenda, the address has changed, we want to run a survey)
- It helps us estimate the actual number of attendees (~60-80% of declared attendees), so we know how much food to order, how many chairs to prepare, etc.
- Meetup sends a confirmation message before the event — it's valuable because many people change their RSVP the same day the event takes place.
- Each event has a "How to find us" section. It's useful for us because our venue is rather hard to find.
- Meetup links look good when shared on Slack and social media (OG tags etc.)
- It schedules events based on a schedule (like the first Wednesday of a month) so we don't have to create them manually

**Problems**

- It's a paid service
- The new pricing is tricky (although our plan hasn't changed yet)
- The comment section is rather primitive
- The search functionality is really bad
- Hard to share files (slides, videos, photos)

### GitHub

[Our GitHub organization](https://github.com/WrocTypeScript/) is our source of truth. We have a couple of repositories.

**What it solves**

- [`website`](https://github.com/WrocTypeScript/website) requires no explanation. We thought we needed one, but we have next to 0 traffic there. 
- [`talks`](https://github.com/WrocTypeScript/talks) is the most important one. It offers two things:
  - [Submit your talk](https://github.com/WrocTypeScript/talks/issues/new/choose). You can submit a proposal or an idea for a talk if you don't feel like giving a talk. GitHub templates come in handy. All you have to do is open a new issue.
  - [A Kanban board](https://github.com/WrocTypeScript/talks/projects/1) with all the talks. You can find the previous ones and see what's coming next.
  - FAQ for speakers (see [`README.md`](https://github.com/WrocTypeScript/talks/blob/ec839f1962a97df1703ec06e0b872bfda730805e/README.md))
- [`past-events`](https://github.com/WrocTypeScript/past-events) is for sharing resources after the talks are given.
- `resources` is just for us. We use it to store prints, designs, posters, photos, assets, and other documents.
- `discussion` is just for us. We do retrospectives, discuss budgets, and use GitHub templates to create event checklists. They look like iteration plans — everything is decomposed into microtasks. It's rather clear who's doing what, but it doesn't make sense to assign specific people since you never really know who's going to be around the day the event takes place. That's why we have a lot of organizers (like 9).

**Problems**

- It's a paid service (free for non-profits but you have to have it registered)
- Only 5 seats available for our plan

### Slack

Every organizer already uses it for work, so it felt like a natural choice.

**What it solves**

We use it for

- preparing the agenda,
- forwarding mail sent to `hello@typescript.community` for everyone on the team to see,
- surveys.

**Problems**

- Messages disappear over time

### Typeform

**What it solves**

We used it on occasion to

- see how familiar with TypeScript is our audience
- measure interest in specific topics

**Problems**

No problems here, it's an excellent service (and free).

## Problems still to be solved

- Share recordings and slides in a place where they can be easily discovered
- Put videos on a YouTube/Vimeo channel that's already known (instead of trying to make our little YouTube channel famous which is going to be difficult)
- Give more exposure and credit to the speakers
  - Speaker profile page?
  - Find other talks given by this particular speaker
  - Talk page? So they can share it on their social media and attach transcripts/slides/links (something like Egghead does)
- Attract and encourage new speakers
  - Tips and tricks?
  - Premade presentation templates?
- Giveaways are expensive
  - People seem to like TypeScript stickers but we hardly have any budget for them
  - Same with books

That's how we roll. I hope you will find something useful here 🙇
