### ISSUE TITLE
Docs: Broken Links

### ISSUE THREAD

**Issue by eKhattak** [microsoft/TypeScript-Website#792]
**Page URL:**  https://www.typescriptlang.org/tsconfig

**Issue:** Scroll down to the explanation section, where on the side, you have **Default**, **Release**, and **Related**. There all the Related links are broken. They are supposed to take you to a specific heading section but they redirect you to a new broken page.

**Recommended Fix:**  The fix is pretty easy, just need to modify the paths.

**Browser:** All Browsers.

**NOTE:** I actually know how to fix this issue and I would like to try it out, It will be my first contribution to this repo. I am opening an issue in case if I fail to fix it, so I can ask for help and keep the conversation here in this issue.

**Comment by orta** [comment]
Good luck!

**Comment by eKhattak** [comment]
@orta I'm trying to get a local copy but not able to install dependency (tried both yarn and npm). Never faced this issue before, so I'm not sure about this. Can you guide me, if you have any idea about it?
![image](https://user-images.githubusercontent.com/37709578/88073420-9643a980-cb8f-11ea-9101-fe48f7851590.png)

**Comment by orta** [comment]
It's possible you tried npm before yarn, can you try deleting your node modules and trying again?

**Comment by eKhattak** [comment]
I tried with deleting npm modules and using `yarn install`, didn't work for me. I then removed the whole directory and downloaded fresh clone and tried `yarn install`. That too didn't work

**Comment by orta** [comment]
What does the error message say?

**Comment by eKhattak** [comment]
> What does the error message say? There doesn't look to be one in your screenshot

When I do `yarn install`, this happens. It's very weird. I have never seen such logs before.
This is all the logs that I get.
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ markdown-spellcheck@npm:1.3.1 doesn't provide sinon@1 requested by sinon-as-promised@npm:4.0.3
➤ YN0060: │ tsdx@npm:0.12.3 provides eslint-plugin-react-hooks@npm:2.3.0 [1be15] with version 2.3.0 which doesn't satisfy
1.x requested by eslint-config-react-app@npm:5.1.0
➤ YN0002: │ onigasm@npm:2.2.4 doesn't provide typescript@>=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7
.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >= 3.1.0-dev || >= 3.2.0-dev requested by tslint@npm:5.20.1
➤ YN0002: │ shiki-languages@npm:0.1.6 doesn't provide onigasm@^2.1.0 requested by vscode-textmate@https://github.com/octre
f/vscode-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-languages@npm:0.1.6 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/oct
ref/vscode-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-themes@npm:0.1.5 doesn't provide onigasm@^2.1.0 requested by vscode-textmate@https://github.com/octref/v
scode-textmate.git#commit:e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-themes@npm:0.1.5 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/octref
/vscode-textmate.git#commit:e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki@npm:0.1.6 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/octref/vscode
-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ handbook-epub@workspace:packages/handbook-epub doesn't provide typescript@>=2.7 requested by ts-node@npm:8.10.
2
➤ YN0060: │ typescript-sandbox@workspace:packages/sandbox provides typescript@patch:typescript@npm%3A4.0.0-beta#builtin<co
mpat/typescript>::version=4.0.0-beta&hash=5b02a2 with version 4.0.0-beta which doesn't satisfy >=3.8 <4.0 requested by ts-
jest@npm:26.1.1
➤ YN0002: │ tsconfig-reference@workspace:packages/tsconfig-reference doesn't provide typescript@>=2.7 requested by ts-node
@npm:8.10.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by @uifabric/utilities@n
pm:7.12.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide react@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:7.12
.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by @uifabric/utiliti
es@npm:7.12.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:
7.12.2
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-reac
t@npm:7.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7
.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-
react@npm:7.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@n
pm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-
react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@n
pm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fab
ric-react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-rea
ct@npm:7.94.0
➤ YN0002: │ typescriptlang-org@workspace:packages/typescriptlang-org doesn't provide graphql@^0.13.0 || ^14.0.0 requested
by gatsby-plugin-typegen@npm:1.1.1
➤ YN0060: │ typescriptlang-org@workspace:packages/typescriptlang-org provides typescript@patch:typescript@npm%3A4.0.0-beta
#builtin<compat/typescript>::version=4.0.0-beta&hash=5b02a2 with version 4.0.0-beta which doesn't satisfy >=3.8 <4.0 reque
sted by ts-jest@npm:26.1.1
➤ YN0002: │ gatsby-cli@npm:2.8.30 doesn't provide @types/react@>=16.8.0 requested by ink@npm:2.6.0
➤ YN0002: │ gatsby@npm:2.19.18 [5df2e] doesn't provide @types/react@^15.0.0 || ^16.0.0 requested by react-hot-loader@npm:4
.12.18
➤ YN0002: │ gatsby-plugin-sass@npm:2.1.28 [5df2e] doesn't provide webpack@^3.0.0 || ^4.0.0 requested by sass-loader@npm:7.
3.1
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.27 [5df2e] doesn't provide graphql@^14.1.1 requested by babel-plugin-remove-g
raphql-queries@npm:2.7.23
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-
react@npm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@n
pm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fab
ric-react@npm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-rea
ct@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric
-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@
npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fa
bric-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-re
act@npm:7.94.0
➤ YN0000: └ Completed in 1.03s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ zen-observable-ts@npm:0.8.20 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:1.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:1.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ical2json@git+https://github.com/adrianlee44/ical2json.git#commit:2d5c097feceefe93348d99ca469991c93512a3f6 ca
➤ YN0018: │ ical2json@git+https://github.com/adrianlee44/ical2json.git#commit:2d5c097feceefe93348d99ca469991c93512a3f6: Th
e remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 1.92m
➤ YN0000: Failed with errors in 1.93m
```

**Comment by alvarocamillont** [comment]
I am getting a similar error.
I am using Ubuntu, npm 14(nvm):

`
➤ YN0000: ┌ Resolution step
➤ YN0002: │ markdown-spellcheck@npm:1.3.1 doesn't provide sinon@1 requested by sinon-as-promised@npm:4.0.3
➤ YN0060: │ tsdx@npm:0.12.3 provides eslint-plugin-react-hooks@npm:2.3.0 [1be15] with version 2.3.0 which doesn't satisfy 1.x requested by eslint-config-react-app@npm:5.1.0
➤ YN0002: │ onigasm@npm:2.2.4 doesn't provide typescript@>=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >= 3.1.0-dev || >= 3.2.0-dev requested by tslint@npm:5.20.1
➤ YN0002: │ shiki-languages@npm:0.1.6 doesn't provide onigasm@^2.1.0 requested by vscode-textmate@https://github.com/octref/vscode-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-languages@npm:0.1.6 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/octref/vscode-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-themes@npm:0.1.5 doesn't provide onigasm@^2.1.0 requested by vscode-textmate@https://github.com/octref/vscode-textmate.git#commit:e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki-themes@npm:0.1.5 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/octref/vscode-textmate.git#commit:e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ shiki@npm:0.1.6 doesn't provide oniguruma@^7.0.0 requested by vscode-textmate@https://github.com/octref/vscode-textmate.git#commit=e65aabe2227febda7beaad31dd0fca1228c5ddf3
➤ YN0002: │ handbook-epub@workspace:packages/handbook-epub doesn't provide typescript@>=2.7 requested by ts-node@npm:8.10.2
➤ YN0060: │ typescript-sandbox@workspace:packages/sandbox provides typescript@patch:typescript@npm%3A4.0.0-beta#builtin<compat/typescript>::version=4.0.0-beta&hash=5b02a2 with version 4.0.0-beta which doesn't satisfy >=3.8 <4.0 requested by ts-jest@npm:26.1.1
➤ YN0002: │ tsconfig-reference@workspace:packages/tsconfig-reference doesn't provide typescript@>=2.7 requested by ts-node@npm:8.10.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:7.12.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide react@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:7.12.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:7.12.2
➤ YN0002: │ @uifabric/styling@npm:7.10.11 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by @uifabric/utilities@npm:7.12.2
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/variants@npm:7.1.13 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/fluent-theme@npm:7.1.22 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ typescriptlang-org@workspace:packages/typescriptlang-org doesn't provide graphql@^0.13.0 || ^14.0.0 requested by gatsby-plugin-typegen@npm:1.1.1
➤ YN0060: │ typescriptlang-org@workspace:packages/typescriptlang-org provides typescript@patch:typescript@npm%3A4.0.0-beta#builtin<compat/typescript>::version=4.0.0-beta&hash=5b02a2 with version 4.0.0-beta which doesn't satisfy >=3.8 <4.0 requested by ts-jest@npm:26.1.1
➤ YN0002: │ gatsby-cli@npm:2.8.30 doesn't provide @types/react@>=16.8.0 requested by ink@npm:2.6.0
➤ YN0002: │ gatsby@npm:2.19.18 [5df2e] doesn't provide @types/react@^15.0.0 || ^16.0.0 requested by react-hot-loader@npm:4.12.18
➤ YN0002: │ gatsby-plugin-sass@npm:2.1.28 [5df2e] doesn't provide webpack@^3.0.0 || ^4.0.0 requested by sass-loader@npm:7.3.1
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.27 [5df2e] doesn't provide graphql@^14.1.1 requested by babel-plugin-remove-graphql-queries@npm:2.7.23
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/azure-themes@npm:7.0.28 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide @types/react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide react@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide @types/react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0002: │ @uifabric/theme-samples@npm:7.0.23 doesn't provide react-dom@>=16.8.0 <17.0.0 requested by office-ui-fabric-react@npm:7.94.0
➤ YN0000: └ Completed in 0.78s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yurnalist@npm:1.1.1 can't be found in the cache and will be fetched fr
➤ YN0013: │ zen-observable-ts@npm:0.8.20 can't be found in the cache and will be f
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetc
➤ YN0013: │ zip-stream@npm:1.2.0 can't be found in the cache and will be fetched f
➤ YN0013: │ zwitch@npm:1.0.4 can't be found in the cache and will be fetched from 
➤ YN0000: └ Completed in 7.81s
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.11#builtin<compat/fsevents>::version=1.2.11&hash=495457 The platform linux is incompatible with this module, linking skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.1.2#builtin<compat/fsevents>::version=2.1.2&hash=495457 The platform linux is incompatible with this module, linking skipped.
➤ YN0007: │ husky@npm:4.2.3 must be built because it never did before or the last one failed
➤ YN0007: │ canvas@npm:2.6.1 must be built because it never did before or the last one failed
➤ YN0007: │ node-sass@npm:4.13.1 must be built because it never did before or the last one failed
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never did before or the last one failed
➤ YN0007: │ gatsby-telemetry@npm:1.1.49 must be built because it never did before or the last one failed
➤ YN0007: │ sharp@npm:0.23.4 must be built because it never did before or the last one failed
➤ YN0007: │ node-expat@npm:2.3.18 must be built because it never did before or the last one failed
➤ YN0007: │ spawn-sync@npm:1.0.15 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.6.0 must be built because it never did before or the last one failed
➤ YN0007: │ mozjpeg@npm:6.0.1 must be built because it never did before or the last one failed
➤ YN0007: │ pngquant-bin@npm:5.0.2 must be built because it never did before or the last one failed
➤ YN0007: │ cwebp-bin@npm:5.1.0 must be built because it never did before or the last one failed
➤ YN0009: │ node-expat@npm:2.3.18 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-eb640dbd/build.log)
➤ YN0009: │ node-expat@npm:2.3.18 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-eb640dbd/build.log)
➤ YN0009: │ sharp@npm:0.23.4 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6ff4494a/build.log)
➤ YN0009: │ sharp@npm:0.23.4 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6ff4494a/build.log)
➤ YN0009: │ node-sass@npm:4.13.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-c7424784/build.log)
➤ YN0009: │ node-sass@npm:4.13.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-c7424784/build.log)
➤ YN0007: │ gatsby-cli@npm:2.8.30 must be built because it never did before or the last one failed
➤ YN0007: │ gatsby@npm:2.19.18 [5df2e] must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 1.3m
➤ YN0000: Failed with errors in 1.45m
`

**Comment by orta** [comment]
I've submitted a PR which replaces all of the failing deps - for both of your logs. 

I can't remove sharp, so @alvarocamillont - you'll need to read the logs there to see what's up

**Comment by alvarocamillont** [comment]
Ok!
What type of OS do you use?

**Comment by orta** [comment]
I use a Mac and Windows, and CI runs both linux and windows. 

So, this repo does cover being built on every major OS for every PR - which is why it's strange that you two are having issues.

**Comment by alvarocamillont** [comment]
I see ...
What version of node are you using?

**Comment by orta** [comment]
```
❯ node -v
v13.6.0
❯ yarn -v
2.1.1
```

I think CI uses 14

**Comment by alvarocamillont** [comment]
Ok!
I am gonna try this version with the new PR.

Thanks Orta!

**Comment by orta** [comment]
OK, that's merged into master now

**Comment by orta** [comment]
I've fixed the related links in the tsconfig - thanks for the issue

**Comment by alvarocamillont** [comment]
Hi @orta !
To do the followup, I was able to run the portal locally, it turn out to be my system didn't have the c ++ compiler. For those who have difficulty building the site, try this site https://linuxconfig.org/how-to-install-g-the-c-compiler-on-ubuntu-18-04-bionic-beaver-linux

**Comment by jmdeepak007git** [comment]
@orta @alvarocamillont Hi Guys, how did you guys fix this issue please ? markdown-spellcheck@npm:1.3.1 doesn't provide sinon (p2d3db), requested by sinon-as-promised
